### ISSUE TITLE
pet-surafce pipeline Error: FileNotFoundError: [Errno 2] No such file or directory: '/some/path/to/surf/lh.white_exp-007'

### ISSUE THREAD

**Issue by sungoku** [aramis-lab/clinica#890]
Dear experts,

I am running clinica 0.7.2 using conda env under Ubuntu 22.04. (By the way, it seems now the package networkx default install is v3.0, but it always error when jobs started, so I downgrade to networkx 2.8.8)
After t1-freesurfer pipeline, I ran pet-suface pipeline like this:

clinica run pet-surface BIDS CAPS_SURF 18FFDG pons BIDS/psf.tsv

Then it crashed, saying:
230312-09:16:40,430 nipype.workflow INFO:
     [Node] Finished "_full_pipeline_mapnode46", elapsed time 4447.733547s.
230312-09:16:40,430 nipype.workflow DEBUG:
     Saving results file: '/tmp/tmpm8sqv0sx/pet-surface/full_pipeline_mapnode/mapflow/_full_pipeline_mapnode46/result__full_pipeline_mapnode46.pklz'
230312-09:16:40,430 nipype.workflow WARNING:
     Storing result file without outputs
230312-09:16:40,434 nipype.workflow WARNING:
     [Node] Error on "_full_pipeline_mapnode46" (/tmp/tmpm8sqv0sx/pet-surface/full_pipeline_mapnode/mapflow/_full_pipeline_mapnode46)
230312-09:16:40,435 nipype.utils DEBUG:
     Loading pkl: /tmp/tmpm8sqv0sx/pet-surface/full_pipeline_mapnode/mapflow/_full_pipeline_mapnode46/result__full_pipeline_mapnode46.pklz
230312-09:16:41,414 nipype.workflow INFO:
     [Node] Finished "mris_expand_white", elapsed time 1065.024562s.
230312-09:16:41,414 nipype.workflow DEBUG:
     Saving results file: '/tmp/tmpm8sqv0sx/pet-surface/sub_HC005_ses_M00/_hemi_lh/mris_expand_white/result_mris_expand_white.pklz'
230312-09:16:41,414 nipype.workflow WARNING:
     Storing result file without outputs
230312-09:16:41,415 nipype.workflow WARNING:
     [Node] Error on "sub_HC005_ses_M00.mris_expand_white" (/tmp/tmpm8sqv0sx/pet-surface/sub_HC005_ses_M00/_hemi_lh/mris_expand_white)
230312-09:16:41,417 nipype.utils DEBUG:
     Loading pkl: /tmp/tmpm8sqv0sx/pet-surface/sub_HC005_ses_M00/_hemi_lh/mris_expand_white/result_mris_expand_white.pklz
230312-09:16:41,417 nipype.workflow ERROR:
     Node mris_expand_white.b0 failed to run on host P7920T.
230312-09:16:41,418 nipype.workflow ERROR:
     Saving crash info to /media/dxyx/EXP/Private/WL/E01_PET_LDA/crash-20230312-091641-dxyx-mris_expand_white.b0-19404322-b7c7-4ca7-a57b-c9138c8ea711.pklz
Traceback (most recent call last):
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/plugins/linear.py", line 47, in run
    node.run(updatehash=updatehash)
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node mris_expand_white.

Traceback (most recent call last):
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/shutil.py", line 816, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/media/dxyx/EXP/Private/WL/E01_PET_LDA/CAPS_SURF/subjects/sub-HC005/ses-M00/t1/freesurfer_cross_sectional/sub-HC005_ses-M00/surf/lh.white_exp-007' -> '/tmp/tmpm8sqv0sx/pet-surface/sub_HC005_ses_M00/_hemi_lh/mris_expand_white/lh.white_exp-007'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
    out = function_handle(**args)
  File "<string>", line 49, in mris_expand
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/media/dxyx/EXP/Private/WL/E01_PET_LDA/CAPS_SURF/subjects/sub-HC005/ses-M00/t1/freesurfer_cross_sectional/sub-HC005_ses-M00/surf/lh.white_exp-007'

**Here is the result from nipypecli crash:**

File: /media/dxyx/EXP/Private/WL/E01_PET_LDA/crash-20230312-091641-dxyx-mris_expand_white.b0-19404322-b7c7-4ca7-a57b-c9138c8ea711.pklz
Node: sub_HC005_ses_M00.mris_expand_white
Working directory: /tmp/tmpm8sqv0sx/pet-surface/sub_HC005_ses_M00/_hemi_lh/mris_expand_white

Node inputs:

function_str = def mris_expand(in_surface):
    """mris_expand is using the freesurfer function of the same name. It expands the white input surface toward the pial,
    generating 7 surfaces at 35%, 40%, 45%, 50%, 55%, 60%, 65% of thickness.

    Args:
        (string) in_surface : Path to the input white surface, but must be named lh.white or rh.white, and the folder
            containing the surface file must also have ?h.pial, ?.sphere, ?h.thickness (freesurfer surf folder)

    Returns:
        (list of strings) List of path to the generated surfaces
    """
    import os
    import shutil
    import subprocess
    import sys

    # bug in mris_expand : you are not allowed to write the surfaces elsewhere than in the surf folder
    # -N is a hidden parameter (not documented) that allows the user to specify the number of surface generated between
    # source and final target surface. Here target is 65% of thickness, with 13 surfaces. Then we only keep the surfaces
    # we are interested in.

    out_file = in_surface + "_exp-"
    cmd = "mris_expand -thickness -N 13 " + in_surface + " 0.65 " + out_file
    # If system is MacOS, this export command must be run just before the mri_vol2surf command to bypass MacOs security
    if sys.platform == "darwin":
        cmd = "export DYLD_LIBRARY_PATH=$FREESURFER_HOME/lib/gcc/lib && " + cmd

    subprocess_mris_expand = subprocess.run(
        cmd,
        shell=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    if subprocess_mris_expand.returncode != 0:
        raise ValueError("mris_expand failed, returned non-zero code")

    # Move surface file to the current directory
    out_filelist = [
        out_file + "007",
        out_file + "008",
        out_file + "009",
        out_file + "010",
        out_file + "011",
        out_file + "012",
        out_file + "013",
    ]
    out_in_node = [os.path.abspath("./" + os.path.basename(x)) for x in out_filelist]
    for i in range(len(out_filelist)):
        shutil.move(out_filelist[i], out_in_node[i])

    # Remove useless surfaces (0%, 5%, 10%, 15%, 20%, 25% and 30% of thickness)
    to_remove = [
        out_file + "000",
        out_file + "001",
        out_file + "002",
        out_file + "003",
        out_file + "004",
        out_file + "005",
        out_file + "006",
    ]
    for i in range(len(to_remove)):
        os.remove(to_remove[i])

    return out_in_node

in_surface = /media/dxyx/EXP/Private/WL/E01_PET_LDA/CAPS_SURF/subjects/sub-HC005/ses-M00/t1/freesurfer_cross_sectional/sub-HC005_ses-M00/surf/lh.white

Traceback: 
Traceback (most recent call last):
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/plugins/linear.py", line 47, in run
    node.run(updatehash=updatehash)
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node mris_expand_white.

Traceback (most recent call last):
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/shutil.py", line 816, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/media/dxyx/EXP/Private/WL/E01_PET_LDA/CAPS_SURF/subjects/sub-HC005/ses-M00/t1/freesurfer_cross_sectional/sub-HC005_ses-M00/surf/lh.white_exp-007' -> '/tmp/tmpm8sqv0sx/pet-surface/sub_HC005_ses_M00/_hemi_lh/mris_expand_white/lh.white_exp-007'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
    out = function_handle(**args)
  File "<string>", line 49, in mris_expand
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/dxyx/miniconda3/envs/clinicaEnv/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/media/dxyx/EXP/Private/WL/E01_PET_LDA/CAPS_SURF/subjects/sub-HC005/ses-M00/t1/freesurfer_cross_sectional/sub-HC005_ses-M00/surf/lh.white_exp-007'

I can't figure out why there is no such file lh.white_exp-007. I can see there are couple of files like lh.white_exp-007 in the tmp folder, but the pipeline still failed to copy these files.
How can I make the pipeline correct?
Please help, thank you!

**Comment by NicolasGensollen** [comment]
Hi @sungoku and thanks for reporting.

First of all, I suggest that you upgrade Clinica to the latest available version which is `0.7.3`.
For example, the issue that you mention about networkx is known and was addressed (waiting for upstream fixes) in between `0.7.2` and `0.7.3` (see #875).
It might be the case that other bugs were fixed, and it'd be easier to understand what's going wrong from a fresh `0.7.3` install.

Also, could you provide some additional information that would help us better understand what is happening:

- Freesurfer version
- information on the BIDS dataset (location in your file system, number of subjects/sessions...)

I suspect the problematic subject-session ("sub-HC005_ses-M00") is the first one to be handled. Is this the case or is the pipeline able to run for other subjects/sessions ?

By looking at the stacktrace you provided, I suspect the problem comes from the fact that you're working across multiple file systems. If I understand correctly, the problem happens at this line:

https://github.com/aramis-lab/clinica/blob/54c08e64769f402932984ad0f71943d015c79121/clinica/pipelines/pet_surface/pet_surface_utils.py#L448

where some output files of `mris_expand` are moved from their initial output folder to the current working directory. In your situation, the former is 

`/media/dxyx/EXP/Private/WL/E01_PET_LDA/CAPS_SURF/subjects/sub-HC005/ses-M00/t1/freesurfer_cross_sectional/sub-HC005_ses-M00/surf`

and the later is

`/tmp/tmpm8sqv0sx/pet-surface/sub_HC005_ses_M00/_hemi_lh/mris_expand_white/`

Besides, could you share the content of `/media/dxyx/EXP/Private/WL/E01_PET_LDA/CAPS_SURF/subjects/sub-HC005/ses-M00/t1/freesurfer_cross_sectional/sub-HC005_ses-M00/surf` ? 

I am not sure to understand whether you said the file `lh.white_exp-007` is in there as expected or not.

**Comment by sungoku** [comment]
Hi, @NicolasGensollen ,
Yes, this is the first one to be handled.  My freesurfer version is 7.3.2.
And I have tried clinica0.7.3, the networkx problem somehow still exists, but this can be fixed by manually install networkx 2.8.8. However, clinica 0.7.3 still have this problem.

And, by adding some print in the source code, I figured out that shutil.move() your pointed out produced the problem.
There is `lh.white_expXXX` in the temp folder, like,` /tmp/tmpm8sqv0sx/pet-surface/sub_HC005_ses_M00/_hemi_lh/mris_expand_white/`
but there is no such files in the folder `/media/dxyx/EXP/Private/WL/E01_PET_LDA/CAPS_SURF/subjects/sub-HC005/ses-M00/t1/freesurfer_cross_sectional/sub-HC005_ses-M00/surf` . 
So the move function just fail.

I think this function should switch the input and output, that is, move files from tmp folder to project folder. But this could produce new problem in the next procedure where it needs this files in tmp folder. 

After some try-and-fail, I finally managed to let the pipeline successfully finish. 
In short, I deleted the code around shutil.move, it does not need to move. 

```
def mris_expand(in_surface):
    """mris_expand is using the freesurfer function of the same name. It expands the white input surface toward the pial,
    generating 7 surfaces at 35%, 40%, 45%, 50%, 55%, 60%, 65% of thickness.

    Args:
        (string) in_surface : Path to the input white surface, but must be named lh.white or rh.white, and the folder
            containing the surface file must also have ?h.pial, ?.sphere, ?h.thickness (freesurfer surf folder)

    Returns:
        (list of strings) List of path to the generated surfaces
    """
    import os
    import shutil
    import subprocess
    import sys

    # bug in mris_expand : you are not allowed to write the surfaces elsewhere than in the surf folder
    # -N is a hidden parameter (not documented) that allows the user to specify the number of surface generated between
    # source and final target surface. Here target is 65% of thickness, with 13 surfaces. Then we only keep the surfaces
    # we are interested in.

    out_file = in_surface + "_exp-"
    cmd = "mris_expand -thickness -N 13 " + in_surface + " 0.65 " + out_file
    # If system is MacOS, this export command must be run just before the mri_vol2surf command to bypass MacOs security
    if sys.platform == "darwin":
        cmd = "export DYLD_LIBRARY_PATH=$FREESURFER_HOME/lib/gcc/lib && " + cmd

    subprocess_mris_expand = subprocess.run(
        cmd,
        shell=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    if subprocess_mris_expand.returncode != 0:
        raise ValueError("mris_expand failed, returned non-zero code")

    # Move surface file to the current directory
    out_filelist = [
        out_file + "007",
        out_file + "008",
        out_file + "009",
        out_file + "010",
        out_file + "011",
        out_file + "012",
        out_file + "013",
    ]
    out_in_node = [os.path.abspath("./" + os.path.basename(x)) for x in out_filelist]
    ####### Code I delete here:
    # for i in range(len(out_filelist)):
    #     print("mris_expand copy from WD to t1-freesufer:")
    #     shutil.copy(out_in_node[i], out_filelist[i])

    # Remove useless surfaces (0%, 5%, 10%, 15%, 20%, 25% and 30% of thickness)
    ##### Modified code below:
    _to_remove = os.path.abspath("./" + os.path.basename(out_file))
    to_remove = [
        _to_remove + "000",
        _to_remove + "001",
        _to_remove + "002",
        _to_remove + "003",
        _to_remove + "004",
        _to_remove + "005",
        _to_remove + "006",
    ]
    for i in range(len(to_remove)):
        print("removed " + to_remove[i])
        os.remove(to_remove[i])

    return out_in_node
```

**Comment by sungoku** [comment]
Hi, @NicolasGensollen ,
 I opened an pull request for this issue's fix, so clinica-team can review the changed code. I hope I modified things correctly.
